tf <- tempfile()
td <- tempdir()
download.file("https://d396qusza40orc.cloudfront.net/exdata%2Fdata%2Fhousehold_power_consumption.zip", tf)
file.names <- unzip(tf, exdir = td)
data <- read.table(file.names, header = TRUE, sep = ";")
dateddata <- subset(data, data$Date == "1/2/2007" | data$Date == "2/2/2007")
dateddata$Global_active_power <- as.numeric(dateddata$Global_active_power)
dateddata$Voltage <- as.numeric(dateddata$Voltage)
dateddata$Sub_metering_1 <- as.numeric(dateddata$Sub_metering_1)
dateddata$Sub_metering_2 <- as.numeric(dateddata$Sub_metering_2)
dateddata$Sub_metering_3 <- as.numeric(dateddata$Sub_metering_3)
dateddata$Global_reactive_power <- as.numeric(dateddata$Global_reactive_power)
par(mfrow = c(2,2))
plot(dateddata$Global_active_power/500, type = "l", ylab = "Global Active Power (kilowatts)", xlab = "")
plot(dateddata$Voltage, type = "l", ylab = "Voltage", xlab = "datetime")
plot(dateddata$Sub_metering_1, typ = "l", ylab = "Energy sub metering")
lines(dateddata$Sub_metering_2, typ = "l", col = "red")
lines(dateddata$Sub_metering_3, typ = "l", col = "blue")
legend("topright", c("Sub_metering_1", "Sub_metering_2", "Sub_metering_3"), lty = c(1,1,1), col = c("black", "red", "blue"), cex = 0.25, bty = "n")
plot(dateddata$Global_reactive_power, type = "l", ylab = "Global_reactive_power", xlab = "datetime")