tf <- tempfile()
td <- tempdir()
download.file("https://d396qusza40orc.cloudfront.net/exdata%2Fdata%2Fhousehold_power_consumption.zip", tf)
file.names <- unzip(tf, exdir = td)
data <- read.table(file.names, header = TRUE, sep = ";")
dateddata <- subset(data, data$Date == "1/2/2007" | data$Date == "2/2/2007")
dateddata$Sub_metering_1 <- as.numeric(dateddata$Sub_metering_1)
dateddata$Sub_metering_2 <- as.numeric(dateddata$Sub_metering_2)
dateddata$Sub_metering_3 <- as.numeric(dateddata$Sub_metering_3)
plot(dateddata$Sub_metering_1, typ = "l")
lines(dateddata$Sub_metering_2, typ = "l", col = "red")
lines(dateddata$Sub_metering_3, typ = "l", col = "blue")
legend("topright", c("Sub_metering_1", "Sub_metering_2", "Sub_metering_3"), lty = c(1,1,1), col = c("black", "red", "blue"))